import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/comingsoonone">ComingSoonOne</Link>
        </li>
        <li>
          <Link to="/blogdetails">BlogDetails</Link>
        </li>
        <li>
          <Link to="/contactthree">ContactThree</Link>
        </li>
        <li>
          <Link to="/page">Page</Link>
        </li>
        <li>
          <Link to="/blogtwo">BlogTwo</Link>
        </li>
        <li>
          <Link to="/pricingtwo">PricingTwo</Link>
        </li>
        <li>
          <Link to="/blogone">BlogOne</Link>
        </li>
        <li>
          <Link to="/casestudydetails">CaseStudyDetails</Link>
        </li>
        <li>
          <Link to="/blogthree">BlogThree</Link>
        </li>
        <li>
          <Link to="/contactone">ContactOne</Link>
        </li>
        <li>
          <Link to="/pricingone">PricingOne</Link>
        </li>
        <li>
          <Link to="/signin">SignIn</Link>
        </li>
        <li>
          <Link to="/casestudy">CaseStudy</Link>
        </li>
        <li>
          <Link to="/signinimage">SignInImage</Link>
        </li>
        <li>
          <Link to="/termsandconditions">TermsandConditions</Link>
        </li>
        <li>
          <Link to="/thankyou">Thankyou</Link>
        </li>
        <li>
          <Link to="/contacttwo">ContactTwo</Link>
        </li>
        <li>
          <Link to="/faq">FAQ</Link>
        </li>
        <li>
          <Link to="/aboutus">Aboutus</Link>
        </li>
        <li>
          <Link to="/reviews">Reviews</Link>
        </li>
        <li>
          <Link to="/landingone">LandingOne</Link>
        </li>
        <li>
          <Link to="/landingfour">LandingFour</Link>
        </li>
        <li>
          <Link to="/landingfive">LandingFive</Link>
        </li>
        <li>
          <Link to="/landingthree">LandingThree</Link>
        </li>
        <li>
          <Link to="/landingsix">LandingSix</Link>
        </li>
        <li>
          <Link to="/careerdetails">CareerDetails</Link>
        </li>
        <li>
          <Link to="/landingtwo">LandingTwo</Link>
        </li>
        <li>
          <Link to="/career">Career</Link>
        </li>
        <li>
          <Link to="/comingsoontwo">ComingSoonTwo</Link>
        </li>
        <li>
          <Link to="/landingseven">LandingSeven</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
